services:

  db:
    restart: "no"
    ports:
      - "5432:5432"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    build:
      context: ./backend
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    volumes:
      - ./backend/htmlcov:/app/htmlcov
    env_file:
      - .env
    environment:
      PROJECT_NAME: "ZensusTech"
      POSTGRES_SERVER: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "changethis"
      POSTGRES_DB: "app"
      FIRST_SUPERUSER: "admin@example.com"
      FIRST_SUPERUSER_PASSWORD: "changethis"
      ENVIRONMENT: "local"
      SMTP_HOST: "localhost"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"
    depends_on:
      - db

  frontend:
    restart: "no"
    ports:
      - "9000:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8000
        - NODE_ENV=development
    depends_on:
      - backend
